-- Care Packs: a paid, AI-generated bundle (Growth Plan + Personal Course +
-- Daily Tracker) personalised from a child's completed assessment results.
-- One active pack per (parent, child). Run this in the Supabase SQL editor.

CREATE TABLE IF NOT EXISTS public.care_packs (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id              UUID NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    child_id               BIGINT NOT NULL REFERENCES public.children(id) ON DELETE CASCADE,
    status                 TEXT DEFAULT 'active',
    amount_paid            INTEGER DEFAULT 0,
    growth_plan_json       TEXT,   -- JSON: 4-week personalised growth plan
    course_json            TEXT,   -- JSON: AI-written mini-course
    tracker_json           TEXT,   -- JSON: daily habit tracker template
    tracker_days_remaining INTEGER DEFAULT 28,
    created_at             TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE (parent_id, child_id)
);

CREATE INDEX IF NOT EXISTS idx_care_packs_child_id ON public.care_packs(child_id);
CREATE INDEX IF NOT EXISTS idx_care_packs_parent_id ON public.care_packs(parent_id);
ALTER TABLE public.care_packs DISABLE ROW LEVEL SECURITY;
