-- Tracker Checks Table
-- Stores which daily habit checkboxes a parent has ticked, per child, per week.
--
-- week_key format: 'YYYY-Www' e.g. '2026-W23' (ISO week)
-- habit_idx:  0-based index into the tracker.daily_habits array
-- day_idx:    0=Mon, 1=Tue, ... 6=Sun

CREATE TABLE IF NOT EXISTS public.tracker_checks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  UUID   NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    child_id   BIGINT NOT NULL REFERENCES public.children(id) ON DELETE CASCADE,
    week_key   TEXT   NOT NULL,   -- e.g. '2026-W23'
    habit_idx  INTEGER NOT NULL,  -- which habit row (0-based)
    day_idx    INTEGER NOT NULL,  -- 0=Mon .. 6=Sun
    checked    BOOLEAN NOT NULL DEFAULT true,
    checked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    UNIQUE (parent_id, child_id, week_key, habit_idx, day_idx)
);

CREATE INDEX IF NOT EXISTS idx_tracker_checks_lookup
    ON public.tracker_checks(parent_id, child_id, week_key);

ALTER TABLE public.tracker_checks DISABLE ROW LEVEL SECURITY;
