-- Supabase Schema Initialization for Empower Students
-- Paste this script directly into your Supabase SQL Editor and click 'Run'.

-- 1. Enable any required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CREATE TABLE: partners (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.partners (
    id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    contact_name    TEXT,
    phone           TEXT,
    whatsapp        TEXT,
    email           TEXT,
    city            TEXT,
    referral_code   TEXT UNIQUE NOT NULL,         -- e.g. 'SUNRISE'
    revenue_share   DOUBLE PRECISION DEFAULT 0.30, -- 30% share
    bank_name       TEXT,
    bank_account    TEXT,
    bank_ifsc       TEXT,
    upi_id          TEXT,
    status          TEXT DEFAULT 'active',        -- active | paused | terminated
    notes           TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    last_referral_at TIMESTAMP WITH TIME ZONE
);

-- Disable Row Level Security (RLS) to ensure Next.js Actions can interact freely with it
ALTER TABLE public.partners DISABLE ROW LEVEL SECURITY;

-- 3. CREATE TABLE: parents (Linked to Supabase Auth, optionally attributed to a partner)
CREATE TABLE IF NOT EXISTS public.parents (
    id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    partner_id    UUID REFERENCES public.partners(id) ON DELETE SET NULL,
    whatsapp      TEXT,
    name          TEXT,
    email         TEXT,
    city          TEXT,
    credits       INTEGER DEFAULT 0,
    is_vip        INTEGER DEFAULT 0,
    is_blocked    INTEGER DEFAULT 0,
    referral_code TEXT,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    last_login    TIMESTAMP WITH TIME ZONE
);

-- Disable Row Level Security (RLS)
ALTER TABLE public.parents DISABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_parents_partner ON public.parents(partner_id);

-- 4. CREATE TABLE: children
CREATE TABLE IF NOT EXISTS public.children (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id     UUID NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    gender        TEXT,
    dob           DATE NOT NULL,
    school        TEXT,
    class_grade   TEXT,
    mother_tongue TEXT,
    languages     TEXT,
    diagnosis     TEXT,
    notes         TEXT,
    photo         TEXT,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.children DISABLE ROW LEVEL SECURITY;

-- 5. CREATE TABLE: assessments
CREATE TABLE IF NOT EXISTS public.assessments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id      BIGINT NOT NULL REFERENCES public.children(id) ON DELETE CASCADE,
    module        TEXT NOT NULL,
    age_band      TEXT,
    status        TEXT DEFAULT 'in_progress',
    score         DOUBLE PRECISION,
    level_reached TEXT,
    ai_summary    TEXT,
    flags         TEXT, -- JSON string
    raw_json      TEXT, -- JSON string
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    completed_at  TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_assessments_child_id ON public.assessments(child_id);
CREATE INDEX IF NOT EXISTS idx_assessments_module ON public.assessments(module);
ALTER TABLE public.assessments DISABLE ROW LEVEL SECURITY;

-- 6. CREATE TABLE: child_eval_sessions
CREATE TABLE IF NOT EXISTS public.child_eval_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id         BIGINT NOT NULL REFERENCES public.children(id) ON DELETE CASCADE,
    module           TEXT NOT NULL,
    age_at_session   DOUBLE PRECISION,
    target_turns     INTEGER,
    turn_count       INTEGER DEFAULT 0,
    status           TEXT DEFAULT 'in_progress',
    started_at       TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    last_activity_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    overall_score    DOUBLE PRECISION,
    report_json      TEXT, -- JSON string
    completed_at     TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.child_eval_sessions DISABLE ROW LEVEL SECURITY;

-- 7. CREATE TABLE: child_eval_turns
CREATE TABLE IF NOT EXISTS public.child_eval_turns (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       BIGINT NOT NULL REFERENCES public.child_eval_sessions(id) ON DELETE CASCADE,
    turn_no          INTEGER NOT NULL,
    axis             TEXT,
    difficulty       INTEGER,
    question_json    TEXT,
    answer_json      TEXT,
    is_correct       BOOLEAN,
    score            DOUBLE PRECISION,
    feedback         TEXT,
    ai_meta_json     TEXT,
    response_seconds DOUBLE PRECISION,
    asked_at         TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    answered_at      TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.child_eval_turns DISABLE ROW LEVEL SECURITY;

-- 8. CREATE TABLE: wallet_ledger
CREATE TABLE IF NOT EXISTS public.wallet_ledger (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id     UUID NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    amount        INTEGER NOT NULL,
    balance_after INTEGER,
    service_key   TEXT,
    ref_id        BIGINT,
    reason        TEXT DEFAULT '',
    created_by    TEXT DEFAULT 'system',
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_parent_id ON public.wallet_ledger(parent_id);
ALTER TABLE public.wallet_ledger DISABLE ROW LEVEL SECURITY;

-- 9. CREATE TABLE: referrals
CREATE TABLE IF NOT EXISTS public.referrals (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_parent_id   UUID NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    referred_phone       TEXT,
    referred_email       TEXT,
    child_eval_completed BOOLEAN DEFAULT false,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.referrals DISABLE ROW LEVEL SECURITY;

-- 10. CREATE TABLE: partner_payout_batches
CREATE TABLE IF NOT EXISTS public.partner_payout_batches (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id      UUID NOT NULL REFERENCES public.partners(id) ON DELETE CASCADE,
    period_start    TIMESTAMP WITH TIME ZONE,
    period_end      TIMESTAMP WITH TIME ZONE,
    total_credits   DOUBLE PRECISION NOT NULL,
    total_inr       DOUBLE PRECISION NOT NULL,
    item_count      INTEGER NOT NULL,
    method          TEXT,                         -- upi | bank_transfer | cash | other
    reference       TEXT,                         -- UTR / txn ID
    notes           TEXT,
    paid_by         TEXT,                         -- admin email/user
    paid_at         TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.partner_payout_batches DISABLE ROW LEVEL SECURITY;

-- 11. CREATE TABLE: partner_payouts
CREATE TABLE IF NOT EXISTS public.partner_payouts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id          UUID NOT NULL REFERENCES public.partners(id) ON DELETE CASCADE,
    parent_id           UUID NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    wallet_ledger_id    BIGINT REFERENCES public.wallet_ledger(id) ON DELETE SET NULL,
    service_key         TEXT NOT NULL,
    gross_amount        INTEGER NOT NULL,
    partner_amount      DOUBLE PRECISION NOT NULL,
    share_rate_used     DOUBLE PRECISION NOT NULL,
    status              TEXT DEFAULT 'pending',   -- pending | paid | reversed
    batch_id            BIGINT REFERENCES public.partner_payout_batches(id) ON DELETE SET NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_partner_payouts_partner_status ON public.partner_payouts(partner_id, status);
ALTER TABLE public.partner_payouts DISABLE ROW LEVEL SECURITY;

-- 12. CREATE TABLE: expert_report_orders
CREATE TABLE IF NOT EXISTS public.expert_report_orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id    UUID NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    child_id     BIGINT NOT NULL REFERENCES public.children(id) ON DELETE CASCADE,
    source       TEXT DEFAULT 'paid',
    amount_paid  INTEGER DEFAULT 0,
    status       TEXT DEFAULT 'pending',
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    completed_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.expert_report_orders DISABLE ROW LEVEL SECURITY;

-- 13. CREATE TABLE: specialists
CREATE TABLE IF NOT EXISTS public.specialists (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    role           TEXT NOT NULL,
    qualifications TEXT,
    bio            TEXT,
    photo          TEXT,
    order_no       INTEGER DEFAULT 100,
    active         BOOLEAN DEFAULT true
);

ALTER TABLE public.specialists DISABLE ROW LEVEL SECURITY;

-- 14. CREATE TABLE: payment_orders
CREATE TABLE IF NOT EXISTS public.payment_orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       TEXT UNIQUE NOT NULL,
    parent_id      UUID NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    amount         INTEGER NOT NULL,
    currency       TEXT DEFAULT 'INR',
    status         TEXT DEFAULT 'pending',
    cf_payment_id  TEXT,
    payment_method TEXT,
    raw_response   TEXT,
    credited       INTEGER DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    completed_at   TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_payment_orders_parent_id ON public.payment_orders(parent_id);
ALTER TABLE public.payment_orders DISABLE ROW LEVEL SECURITY;

-- 15. CREATE TABLE: parent_feedback
CREATE TABLE IF NOT EXISTS public.parent_feedback (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id      UUID NOT NULL REFERENCES public.parents(id) ON DELETE CASCADE,
    child_id       BIGINT REFERENCES public.children(id) ON DELETE SET NULL,
    author         TEXT,
    body           TEXT NOT NULL,
    seen_by_parent INTEGER DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.parent_feedback DISABLE ROW LEVEL SECURITY;

-- 16. CREATE TABLE: service_prices
CREATE TABLE IF NOT EXISTS public.service_prices (
    service_key TEXT PRIMARY KEY,
    label       TEXT,
    price       INTEGER DEFAULT 0,
    audience    TEXT DEFAULT 'parent',
    is_active   BOOLEAN DEFAULT true,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.service_prices DISABLE ROW LEVEL SECURITY;


-- ── SEED INITIAL DATA ──

-- Seed specialists
INSERT INTO public.specialists (name, role, qualifications, bio, photo, order_no, active) VALUES
('Senior Occupational Therapist', 'Occupational Therapist', 'M.O.T. (Paeds)', 'Sensory integration, fine-motor and ADL support for children with developmental delays, ASD and ADHD.', 'ot.jpg', 10, true),
('Senior Speech-Language Pathologist', 'Speech Therapist', 'M.A.S.L.P., R.C.I. licensed', 'Articulation, fluency (stuttering), language delay, AAC and feeding therapy.', 'speech.jpg', 20, true),
('Clinical Child Psychologist', 'Psychologist', 'M.Phil. Clinical Psychology', 'Developmental and IQ assessments, emotional regulation, behaviour therapy, parent counselling.', 'psychologist.jpg', 30, true),
('Consultant Paediatric Neurologist', 'Neurologist', 'DM Neurology', 'Epilepsy, neurodevelopmental disorders, headache, ADHD/ASD medical evaluation.', 'neurologist.jpg', 40, true),
('Consultant Paediatrician', 'Paediatrician', 'MD Paediatrics', 'Growth, immunisation, nutrition, common childhood illnesses.', 'paeds.jpg', 50, true),
('Family Counsellor', 'Counsellor', 'M.A. Counselling Psychology', 'Parent-child relationship, school refusal, exam stress, adolescence guidance.', 'counsellor.jpg', 60, true),
('Special Educator', 'Special Educator', 'B.Ed (Special Ed.)', 'Individualised learning plans for SLD (dyslexia, dyscalculia), ASD and intellectual disability.', 'special_ed.jpg', 70, true)
ON CONFLICT (id) DO NOTHING;

-- Seed service prices
INSERT INTO public.service_prices (service_key, label, price, audience, is_active) VALUES
('health', 'Health screening', 3, 'parent', true),
('mind_power', 'Mind power screening', 3, 'parent', true),
('emotions', 'Emotions screening', 3, 'parent', true),
('behavior', 'Behaviour screening', 3, 'parent', true),
('special_talent', 'Special talent screener', 3, 'parent', true),
('parent_index', 'Parent self-rating', 3, 'parent', true),
('general_awareness', 'General awareness quiz', 5, 'parent', true),
('math', 'Maths adaptive test', 5, 'parent', true),
('language', 'Language & reading', 5, 'parent', true),
('speech', 'Speech (audio + AI)', 10, 'parent', true),
('spontaneous', 'Spontaneous speech (audio + AI)', 10, 'parent', true),
('diet', 'Diet plan (AI)', 20, 'parent', true),
('pulse_check', 'Pulse / breath check', 2, 'parent', true),
('comprehensive_report', 'Comprehensive AI report (1 / child)', 50, 'parent', true)
ON CONFLICT (service_key) DO UPDATE 
SET label = EXCLUDED.label, price = EXCLUDED.price, audience = EXCLUDED.audience, is_active = EXCLUDED.is_active;


-- ── 17. TABLES FOR SPEECH EVAL & PARENT REFLECTION ──

-- Alter parents table to support free evaluation tracking
ALTER TABLE public.parents ADD COLUMN IF NOT EXISTS free_eval_used_at TIMESTAMP WITH TIME ZONE;

-- CREATE TABLE: eval_sessions
CREATE TABLE IF NOT EXISTS public.eval_sessions (
    id              SERIAL PRIMARY KEY,
    parent_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    child_id        INTEGER NOT NULL REFERENCES public.children(id) ON DELETE CASCADE,
    module          TEXT NOT NULL,                 -- 'mod_speech_basic' etc.
    status          TEXT NOT NULL DEFAULT 'in_progress',  -- in_progress | completed | abandoned
    is_free         BOOLEAN NOT NULL DEFAULT false,
    cost_paid       INTEGER NOT NULL DEFAULT 0,    -- in rupees (0 for free, 59 for paid)
    started_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    completed_at    TIMESTAMP WITH TIME ZONE,
    current_level   INTEGER NOT NULL DEFAULT 3,    -- 1..5; starts mid
    questions_asked INTEGER NOT NULL DEFAULT 0,
    final_level     INTEGER,                       -- the level the engine settled on
    final_pct       INTEGER,                       -- percentile-ish summary (0-100)
    report_md       TEXT,                           -- AI-generated markdown report
    report_md_hi    TEXT,                           -- Hindi version (Phase 3 polish)
    sample_exercise_md TEXT                          -- one sample exercise for upsell
);

CREATE INDEX IF NOT EXISTS idx_eval_sessions_parent ON public.eval_sessions(parent_id, status);
CREATE INDEX IF NOT EXISTS idx_eval_sessions_child ON public.eval_sessions(child_id, module);
ALTER TABLE public.eval_sessions DISABLE ROW LEVEL SECURITY;

-- CREATE TABLE: eval_questions
CREATE TABLE IF NOT EXISTS public.eval_questions (
    id              SERIAL PRIMARY KEY,
    session_id      INTEGER NOT NULL REFERENCES public.eval_sessions(id) ON DELETE CASCADE,
    seq_no          INTEGER NOT NULL,              -- 1, 2, 3...
    level           INTEGER NOT NULL,              -- 1..5 the level this q was generated for
    question_type   TEXT NOT NULL,                 -- mcq | naming | fill_in | describe
    prompt          TEXT NOT NULL,                 -- the question text shown to user
    options_json    TEXT,                          -- JSON array of MCQ options if applicable
    expected        TEXT,                          -- expected/correct answer (free-text 'gold')
    image_concept   TEXT,                          -- short description if image is referenced
    asked_at        TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    answered_at     TIMESTAMP WITH TIME ZONE,      -- when the user submitted
    time_seconds    INTEGER,                       -- how long they took
    user_answer     TEXT,                          -- what they entered/picked
    answer_mode     TEXT DEFAULT 'text',           -- text | voice
    acoustic_json   TEXT,                          -- JSON of acoustic features when answer_mode=voice
    audio_path      TEXT,                          -- relative path to stored audio file (voice mode)
    is_correct      INTEGER,                       -- 0/1 after AI scoring (NULL = not yet scored)
    ai_verdict      TEXT,                          -- 'correct_fast' | 'correct_slow' | 'wrong_fast' | 'wrong_slow'
    next_level      INTEGER                        -- the level the engine decided for the NEXT q
);

CREATE INDEX IF NOT EXISTS idx_eval_questions_session ON public.eval_questions(session_id, seq_no);
ALTER TABLE public.eval_questions DISABLE ROW LEVEL SECURITY;

-- CREATE TABLE: parent_reflect_sessions
CREATE TABLE IF NOT EXISTS public.parent_reflect_sessions (
    id                  SERIAL PRIMARY KEY,
    parent_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    child_id            INTEGER REFERENCES public.children(id) ON DELETE SET NULL,  -- which child this is about
    status              TEXT NOT NULL DEFAULT 'in_progress',  -- in_progress | completed | abandoned
    cost_paid           INTEGER NOT NULL DEFAULT 0,           -- always 499 (no free tier)
    started_at          TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    last_activity_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    completed_at        TIMESTAMP WITH TIME ZONE,
    current_phase       INTEGER NOT NULL DEFAULT 1,            -- 1..10
    turn_count          INTEGER NOT NULL DEFAULT 0,            -- how many AI questions have been asked
    followup_count      INTEGER NOT NULL DEFAULT 0,
    -- Final outputs (filled on close, both via Sonnet)
    parent_summary_md   TEXT,                                  -- the warm, supportive report parent sees
    parent_action_md    TEXT,                                  -- 'one thing to try this week'
    admin_clinical_md   TEXT,                                  -- clinical view (NCI staff only)
    admin_risk_level    TEXT,                                  -- 'green' | 'amber' | 'red'
    admin_follow_up_by  TEXT,                                  -- ISO datetime — when NCI must call back
    generated_at        TIMESTAMP WITH TIME ZONE,
    -- Aggregated risk signals (0..1 each, computed on close)
    sig_marital_stress  REAL DEFAULT 0,
    sig_in_law_stress   REAL DEFAULT 0,
    sig_parent_burnout  REAL DEFAULT 0,
    sig_child_distress  REAL DEFAULT 0,
    sig_isolation       REAL DEFAULT 0,
    sig_safety_red_flag INTEGER DEFAULT 0                      -- 0 or 1
);

CREATE INDEX IF NOT EXISTS idx_pr_sessions_parent ON public.parent_reflect_sessions(parent_id, status);
CREATE INDEX IF NOT EXISTS idx_pr_sessions_admin  ON public.parent_reflect_sessions(status, admin_risk_level, completed_at);
ALTER TABLE public.parent_reflect_sessions DISABLE ROW LEVEL SECURITY;

-- CREATE TABLE: parent_reflect_turns
CREATE TABLE IF NOT EXISTS public.parent_reflect_turns (
    id                  SERIAL PRIMARY KEY,
    session_id          INTEGER NOT NULL REFERENCES public.parent_reflect_sessions(id) ON DELETE CASCADE,
    turn_no             INTEGER NOT NULL,                      -- 1, 2, 3...
    phase               INTEGER NOT NULL,                      -- 1..10 phase the AI was operating in
    question            TEXT NOT NULL,                         -- AI's question this turn
    question_intent     TEXT,                                  -- probe | reframe | forward | slow | challenge | close
    asked_at            TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    -- Parent's response (set when answer comes in)
    transcript          TEXT,
    answered_at         TIMESTAMP WITH TIME ZONE,
    time_seconds        INTEGER,
    acoustic_json       TEXT,                                  -- WPM, duration, pause_count, silence_ratio, volume_variance, time_to_first_speech_sec, transcript_confidence
    emotions_json       TEXT,                                  -- 11 intensities + felt_sense (from Haiku emotion call)
    -- AI's interpretation
    ai_reflection       TEXT,                                  -- 1-2 sentences mirroring what parent said
    ai_tone_insight     TEXT,                                  -- 1 sentence on voice + words combined
    signals_json        TEXT                                   -- per-turn signals snapshot
);

CREATE INDEX IF NOT EXISTS idx_pr_turns_session ON public.parent_reflect_turns(session_id, turn_no);
ALTER TABLE public.parent_reflect_turns DISABLE ROW LEVEL SECURITY;

-- Seed service prices
INSERT INTO public.service_prices (service_key, label, price, audience, is_active) VALUES
('mod_speech_eval', 'Speech & Language Evaluation', 59, 'parent', true),
('plan_speech_week1', 'Speech 1-Week Plan', 99, 'parent', true),
('mod_parent_reflect', 'Parent Reflection (with psychologist callback)', 499, 'parent', true)
ON CONFLICT (service_key) DO UPDATE 
SET label = EXCLUDED.label, price = EXCLUDED.price, audience = EXCLUDED.audience, is_active = EXCLUDED.is_active;

