<?php
/**
 * includes/course_engine.php
 *
 * 7-day speech improvement course — engine.
 *
 * Lifecycle:
 *   1. Parent finishes an eval → sees the 5-axis report → clicks Buy ₹99/₹199/₹350
 *   2. course-start.php charges wallet, calls course_create()
 *      - new course row with anchor_sentence + weak_axes JSON + sku
 *   3. Parent visits /course.php?id=N → today's task generated + cached
 *      - same task all day; reusing day records latest recording
 *   4. Child does the task with parent (2/5/10 min based on SKU)
 *   5. Child records the ANCHOR SENTENCE (same all 7 days)
 *   6. course-day.php scores the anchor recording (5-axis snapshot)
 *      and advances last_active_at + completed_at on day row
 *   7. Tomorrow: parent comes back → next day's task auto-generated
 *
 * Missed-days rule (strict): if today is 2+ days after last completion,
 * course is marked failed. 1 day grace = OK. No refunds.
 *
 * Day 8: course status = 'completed'. /course.php shows final progress chart
 * + delta vs original eval + Week 2 upsell.
 *
 * Reuses: eval_clinical.php's _clinical_compute_priors() for axis scoring,
 * wallet helpers, claude.php's claude_json() for task generation.
 */

require_once __DIR__ . '/claude.php';
require_once __DIR__ . '/eval_clinical.php';  // for _clinical_compute_priors


// ─────────────────────────────────────────────────────────────
// Schema migration (idempotent)
// ─────────────────────────────────────────────────────────────
function _course_ensure_schema(): void {
    static $done = false;
    if ($done) return;

    db()->exec("CREATE TABLE IF NOT EXISTS eval_courses (
        id                INTEGER PRIMARY KEY AUTOINCREMENT,
        parent_id         INTEGER NOT NULL,
        child_id          INTEGER NOT NULL REFERENCES children(id) ON DELETE CASCADE,
        eval_session_id   INTEGER REFERENCES eval_sessions(id) ON DELETE SET NULL,
        sku               TEXT NOT NULL,         -- 'course_speech_2min' | '5min' | '10min'
        daily_minutes     INTEGER NOT NULL,      -- 2 | 5 | 10
        price_paid        INTEGER NOT NULL,      -- 99 | 199 | 350
        weak_axes_json    TEXT,                  -- JSON: top 2 weakest axes from eval, with baseline scores
        anchor_sentence   TEXT NOT NULL,         -- same sentence all 7 days
        anchor_lang       TEXT NOT NULL DEFAULT 'hi',   -- 'hi' or 'en'
        status            TEXT NOT NULL DEFAULT 'active',  -- active | completed | failed | abandoned
        started_at        TEXT DEFAULT CURRENT_TIMESTAMP,
        completed_at      TEXT,
        last_active_at    TEXT,
        notes             TEXT
    );");
    db()->exec("CREATE INDEX IF NOT EXISTS idx_courses_parent ON eval_courses(parent_id, status);");
    db()->exec("CREATE INDEX IF NOT EXISTS idx_courses_child ON eval_courses(child_id);");

    db()->exec("CREATE TABLE IF NOT EXISTS eval_course_days (
        id                INTEGER PRIMARY KEY AUTOINCREMENT,
        course_id         INTEGER NOT NULL REFERENCES eval_courses(id) ON DELETE CASCADE,
        day_no            INTEGER NOT NULL,         -- 1..7
        task_md           TEXT,                     -- parent-facing task instructions (generated by Claude)
        task_target_axis  TEXT,                     -- which axis this day targets (articulation/fluency/etc)
        task_generated_at TEXT,
        recording_path    TEXT,                     -- audio of child reading anchor sentence
        transcript        TEXT,                     -- Web Speech transcript of the recording
        acoustic_json     TEXT,                     -- WPM, confidence, etc — same shape as eval_questions
        axis_snapshot_json TEXT,                    -- 5-axis scores for THIS day's anchor reading
        parent_note       TEXT,
        completed_at      TEXT,
        UNIQUE(course_id, day_no)
    );");
    db()->exec("CREATE INDEX IF NOT EXISTS idx_course_days ON eval_course_days(course_id, day_no);");

    // Seed the 3 SKU prices (idempotent INSERT OR REPLACE)
    try {
        $skus = [
            ['course_speech_2min',  '7-Day Speech Course — 2 min/day',  99,  'parent', 1],
            ['course_speech_5min',  '7-Day Speech Course — 5 min/day',  199, 'parent', 1],
            ['course_speech_10min', '7-Day Speech Course — 10 min/day', 350, 'parent', 1],
        ];
        foreach ($skus as $s) {
            db()->prepare("INSERT OR REPLACE INTO service_prices
                           (service_key, label, price, audience, is_active)
                           VALUES (?, ?, ?, ?, ?)")
               ->execute($s);
        }
    } catch (Throwable $e) {
        error_log('[course schema seed prices] ' . $e->getMessage());
    }

    $done = true;
}


// ─────────────────────────────────────────────────────────────
// Anchor sentence picker — hardcoded library
// ─────────────────────────────────────────────────────────────
/**
 * Returns ['sentence' => string, 'lang' => 'hi'|'en', 'target_axis' => string]
 *
 * The anchor sentence is picked based on the weakest axis in the clinical
 * report. Each sentence is engineered to PROBE the targeted weakness, so
 * day-to-day variation in the recording reveals real progress.
 *
 * Picked once at course creation, used for all 7 days (clean comparison).
 */
function course_pick_anchor_sentence(array $clinical_axes, bool $is_hindi): array {
    // Find the lowest-scoring axis (excluding null/N-A like narrative when not assessed)
    $weakest_axis = 'fluency';
    $weakest_score = 101;
    foreach (['articulation','fluency','vocabulary','grammar','narrative'] as $k) {
        $score = $clinical_axes[$k]['score'] ?? null;
        if ($score === null) continue;
        if ((int)$score < $weakest_score) {
            $weakest_score = (int)$score;
            $weakest_axis = $k;
        }
    }

    // Sentence library — one Hindi + English version per axis target
    $lib = [
        'articulation' => [
            // Heavy on consonant blends, retroflexes (ट, ठ, ड), aspirated sounds
            'hi' => 'मेरे प्यारे दादा-दादी कल गाँव से ट्रेन में आए और सब बच्चों के लिए मिठाई लाए।',
            'en' => 'My grandparents brought sweet little chocolates and cricket bats from the big train station.',
        ],
        'fluency' => [
            // Long enough to require smooth flow, simple words so flow itself is the test
            'hi' => 'आज सुबह मैं उठा, ब्रश किया, नाश्ता खाया और फिर अपने दोस्तों के साथ खेलने बाहर गया।',
            'en' => 'This morning I woke up, brushed my teeth, ate breakfast, and then went outside to play with my friends.',
        ],
        'vocabulary' => [
            // Variety of word types — nouns, verbs, adjectives, time markers
            'hi' => 'कल शाम को मेरी छोटी बहन ने अपनी नई नीली साइकिल पर खूब तेज़ चलाई।',
            'en' => 'Yesterday evening my little sister rode her brand new blue bicycle very fast around the park.',
        ],
        'grammar' => [
            // Multiple tenses, postpositions, sentence connectors
            'hi' => 'जब बारिश हो रही थी, मेरी माँ ने मुझे छाता दिया और मैंने स्कूल जाते समय खूब मज़े किए।',
            'en' => 'When it was raining, my mother gave me an umbrella and I had so much fun on my way to school.',
        ],
        'narrative' => [
            // Sequencing + cause/effect + 3+ events
            'hi' => 'पहले मैंने अपना होमवर्क पूरा किया, फिर खाना खाया, और अंत में दादी के साथ कहानी सुनी।',
            'en' => 'First I finished all of my homework, then I ate my dinner, and finally I listened to a story with grandma.',
        ],
    ];

    $entry = $lib[$weakest_axis] ?? $lib['fluency'];
    $sentence = $is_hindi ? $entry['hi'] : $entry['en'];

    return [
        'sentence'    => $sentence,
        'lang'        => $is_hindi ? 'hi' : 'en',
        'target_axis' => $weakest_axis,
    ];
}


// ─────────────────────────────────────────────────────────────
// Course creation
// ─────────────────────────────────────────────────────────────
/**
 * Create a new course row. Caller has already verified payment.
 *
 * Returns ['ok' => bool, 'course_id' => int|null, 'error' => string|null].
 */
function course_create(int $parent_id, int $child_id, string $sku, ?int $eval_session_id = null): array {
    _course_ensure_schema();

    $sku_meta = [
        'course_speech_2min'  => ['minutes' =>  2, 'price' =>  99],
        'course_speech_5min'  => ['minutes' =>  5, 'price' => 199],
        'course_speech_10min' => ['minutes' => 10, 'price' => 350],
    ];
    if (!isset($sku_meta[$sku])) {
        return ['ok' => false, 'course_id' => null, 'error' => 'Unknown SKU'];
    }

    // Verify child belongs to this parent
    $cst = db()->prepare("SELECT id, mother_tongue FROM children WHERE id = ? AND parent_id = ?");
    $cst->execute([$child_id, $parent_id]);
    $child = $cst->fetch();
    if (!$child) {
        return ['ok' => false, 'course_id' => null, 'error' => 'Child not found'];
    }
    $is_hindi = preg_match('/[\x{0900}-\x{097F}]/u', (string)$child['mother_tongue'])
              || stripos((string)$child['mother_tongue'], 'hindi') !== false;

    // Pull the clinical axes from the eval session
    $clinical_axes = [];
    $eval_age = null;
    if ($eval_session_id) {
        $est = db()->prepare("SELECT clinical_report_json FROM eval_sessions WHERE id = ? AND parent_id = ?");
        $est->execute([$eval_session_id, $parent_id]);
        $json = $est->fetchColumn();
        if ($json) {
            $decoded = json_decode($json, true);
            if (is_array($decoded)) $clinical_axes = $decoded;
        }
    }
    // Fallback: blank axes (course can still work, just generic anchor)
    if (empty($clinical_axes)) {
        $clinical_axes = [
            'articulation' => ['score' => 70],
            'fluency'      => ['score' => 70],
            'vocabulary'   => ['score' => 70],
            'grammar'      => ['score' => 70],
            'narrative'    => ['score' => 70],
        ];
    }

    // Pick the anchor sentence based on weakest axis
    $anchor = course_pick_anchor_sentence($clinical_axes, (bool)$is_hindi);

    // Snapshot the weak axes (top 2 lowest) so we can target tasks
    $axis_scores = [];
    foreach (['articulation','fluency','vocabulary','grammar','narrative'] as $k) {
        $s = $clinical_axes[$k]['score'] ?? null;
        if ($s !== null) $axis_scores[$k] = (int)$s;
    }
    asort($axis_scores);
    $weak_two = array_slice(array_keys($axis_scores), 0, 2);
    $weak_json = json_encode([
        'weakest_axis' => $anchor['target_axis'],
        'weak_two'     => $weak_two,
        'baseline'     => $axis_scores,
    ], JSON_UNESCAPED_UNICODE);

    db()->prepare("INSERT INTO eval_courses
                   (parent_id, child_id, eval_session_id, sku, daily_minutes, price_paid,
                    weak_axes_json, anchor_sentence, anchor_lang, last_active_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)")
       ->execute([
           $parent_id, $child_id, $eval_session_id, $sku,
           $sku_meta[$sku]['minutes'], $sku_meta[$sku]['price'],
           $weak_json, $anchor['sentence'], $anchor['lang']
       ]);

    return ['ok' => true, 'course_id' => (int) db()->lastInsertId(), 'error' => null];
}


// ─────────────────────────────────────────────────────────────
// Today-day calculation + missed-day check
// ─────────────────────────────────────────────────────────────
/**
 * Returns:
 *   ['day_no' => 1-7, 'status' => 'active'|'failed'|'completed',
 *    'days_since_last' => int, 'failed_reason' => string|null]
 *
 * Strict missed-day rule:
 *   - If 0 days completed yet, parent must start within 7 days of course creation
 *   - If N days completed (N<7), parent must complete day N+1 within 2 days
 *     of completing day N. Otherwise course = failed.
 *   - 1 day grace is built in (= "within 2 days" = today + tomorrow OK; day-after = fail).
 */
function course_today_day(int $course_id): array {
    $st = db()->prepare("SELECT * FROM eval_courses WHERE id = ?");
    $st->execute([$course_id]);
    $course = $st->fetch();
    if (!$course) {
        return ['day_no' => 0, 'status' => 'not_found', 'days_since_last' => 0, 'failed_reason' => 'Course not found'];
    }

    if ($course['status'] === 'completed') {
        return ['day_no' => 7, 'status' => 'completed', 'days_since_last' => 0, 'failed_reason' => null];
    }
    if ($course['status'] === 'failed' || $course['status'] === 'abandoned') {
        return ['day_no' => 0, 'status' => $course['status'], 'days_since_last' => 0,
                'failed_reason' => $course['notes'] ?: 'Course was discontinued'];
    }

    // Count completed days
    $dst = db()->prepare("SELECT MAX(day_no) AS max_day, MAX(completed_at) AS last_day_at
                          FROM eval_course_days
                          WHERE course_id = ? AND completed_at IS NOT NULL");
    $dst->execute([$course_id]);
    $done = $dst->fetch();
    $last_done_day = (int)($done['max_day'] ?? 0);
    $last_day_at   = $done['last_day_at'] ?? $course['started_at'];

    $days_since_last = floor((time() - strtotime((string)$last_day_at . ' UTC')) / 86400);
    if ($days_since_last < 0) $days_since_last = 0;

    // If 7 days complete → mark completed (lazy update)
    if ($last_done_day >= 7) {
        db()->prepare("UPDATE eval_courses SET status = 'completed', completed_at = CURRENT_TIMESTAMP WHERE id = ?")
           ->execute([$course_id]);
        return ['day_no' => 7, 'status' => 'completed', 'days_since_last' => 0, 'failed_reason' => null];
    }

    // Strict missed-day rule
    if ($last_done_day === 0) {
        // No days done yet — parent has 7 days from course creation to start day 1
        if ($days_since_last >= 7) {
            $reason = 'Course not started within 7 days of purchase.';
            db()->prepare("UPDATE eval_courses SET status = 'failed', notes = ? WHERE id = ?")
               ->execute([$reason, $course_id]);
            return ['day_no' => 0, 'status' => 'failed', 'days_since_last' => $days_since_last, 'failed_reason' => $reason];
        }
    } else {
        // Days done → next day must be within 2 calendar days of the last completion
        if ($days_since_last >= 2) {
            $reason = "Missed too many days. Last completed Day {$last_done_day}, now {$days_since_last} days ago. Max gap is 1 day.";
            db()->prepare("UPDATE eval_courses SET status = 'failed', notes = ? WHERE id = ?")
               ->execute([$reason, $course_id]);
            return ['day_no' => 0, 'status' => 'failed', 'days_since_last' => $days_since_last, 'failed_reason' => $reason];
        }
    }

    return [
        'day_no'          => $last_done_day + 1,
        'status'          => 'active',
        'days_since_last' => (int)$days_since_last,
        'failed_reason'   => null,
    ];
}


// ─────────────────────────────────────────────────────────────
// Daily task generation (one Claude call, cached)
// ─────────────────────────────────────────────────────────────
/**
 * Generate today's task using Claude. Cached in eval_course_days.task_md
 * so re-visiting /course.php doesn't re-call Claude.
 *
 * Tasks rotate through weak axes — Day 1 = weakest, Day 2 = 2nd weakest,
 * Day 3 = weakest again, etc. So a 7-day course gives the weakest axis
 * 4 days of focus and the 2nd-weakest 3 days.
 */
function course_generate_daily_task(int $course_id, int $day_no): array {
    $st = db()->prepare("SELECT * FROM eval_courses WHERE id = ?");
    $st->execute([$course_id]);
    $course = $st->fetch();
    if (!$course) return ['ok' => false, 'error' => 'Course not found'];

    // Check cache
    $cst = db()->prepare("SELECT task_md, task_target_axis FROM eval_course_days WHERE course_id = ? AND day_no = ?");
    $cst->execute([$course_id, $day_no]);
    $cached = $cst->fetch();
    if ($cached && !empty($cached['task_md'])) {
        return [
            'ok'           => true,
            'task_md'      => $cached['task_md'],
            'target_axis'  => $cached['task_target_axis'],
            'from_cache'   => true,
        ];
    }

    // Pick this day's target axis (rotate through weak axes)
    $weak = json_decode($course['weak_axes_json'] ?: '{}', true) ?: [];
    $weak_two = $weak['weak_two'] ?? ['fluency', 'narrative'];
    if (count($weak_two) < 2) $weak_two[] = 'fluency';
    $target_axis = ($day_no % 2 === 1) ? $weak_two[0] : $weak_two[1];

    // Pull child info
    $cst2 = db()->prepare("SELECT name, dob, mother_tongue FROM children WHERE id = ?");
    $cst2->execute([$course['child_id']]);
    $child = $cst2->fetch();
    $age_yrs = round((float) calc_age_years($child['dob']), 1);
    $minutes = (int)$course['daily_minutes'];
    $is_hindi = $course['anchor_lang'] === 'hi';

    // Get baseline scores from clinical report (for task calibration)
    $baseline = $weak['baseline'] ?? [];
    $axis_baseline_score = (int)($baseline[$target_axis] ?? 60);

    $axis_descriptions = [
        'articulation' => 'speech clarity — clear production of consonants, vowels, blends',
        'fluency'      => 'smooth speech flow — rate, rhythm, hesitation reduction',
        'vocabulary'   => 'expanding word range — new words used in real contexts',
        'grammar'      => 'sentence structure — tenses, agreement, function words',
        'narrative'    => 'multi-sentence storytelling — sequencing, detail, coherence',
    ];

    $sys = "You are a senior speech-language pathologist at EmpowerStudents. "
         . "Design ONE daily home-practice task for a child in our 7-day course.\n\n"
         . "Tone: warm, specific, immediately actionable for a parent. Indian household context.\n"
         . "The task takes EXACTLY {$minutes} minutes. Use simple household materials only.\n\n"
         . "Output JSON only:\n"
         . "{\n"
         . "  \"title\": \"Short evocative task name (e.g. 'Mirror Sound Game' or 'Picture Story Chain')\",\n"
         . "  \"task_md\": \"Markdown content: ### What you need (1 line list) ### How to play (numbered steps 1-5) ### What to watch for (2-3 bullets)\"\n"
         . "}\n\n"
         . "RULES:\n"
         . "- Task duration: {$minutes} minutes EXACTLY. Tasks for 2-min courses are very simple, 1-2 quick rounds. Tasks for 10-min are longer with build-up.\n"
         . "- Target axis: {$target_axis} ({$axis_descriptions[$target_axis]}).\n"
         . "- Child's baseline on this axis: {$axis_baseline_score}/100. Calibrate difficulty.\n"
         . "- Language: " . ($is_hindi ? "Hindi (Devanagari) for instructions to the child, Hindi+English for parent guidance" : "English throughout") . "\n"
         . "- Day {$day_no} of 7. Build on what came before if possible.\n"
         . "- DO NOT mention the anchor sentence — that's a separate end-of-session recording, not part of the task.\n";

    $user = "Child: {$child['name']}, age {$age_yrs} years\n"
          . "Day {$day_no} of 7-day course\n"
          . "Today's target: {$target_axis} ({$axis_descriptions[$target_axis]})\n"
          . "Child's score on this axis at eval: {$axis_baseline_score}/100\n"
          . "Task duration: {$minutes} minutes\n\n"
          . "Generate one specific task. JSON only.";

    $j = claude_json($sys, $user, 1200, 0.6);
    if (!is_array($j) || empty($j['task_md'])) {
        error_log("[course_generate_daily_task] Claude returned invalid for course=$course_id day=$day_no");
        // Fallback canned task
        $fallback_md = "### What you need\n- 5 minutes of quiet time\n\n### How to play\n1. Sit with " . $child['name'] . " somewhere comfortable.\n2. Ask them to tell you one thing they did today.\n3. Encourage longer answers by asking 'and then what happened?'\n4. Celebrate every attempt.\n\n### What to watch for\n- Confidence in answering\n- Length of response\n- New words used";
        $j = ['title' => "Day {$day_no} Practice", 'task_md' => $fallback_md];
    }

    // Cache it on the day row (upsert)
    db()->prepare("INSERT INTO eval_course_days (course_id, day_no, task_md, task_target_axis, task_generated_at)
                   VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
                   ON CONFLICT(course_id, day_no) DO UPDATE SET
                     task_md = excluded.task_md,
                     task_target_axis = excluded.task_target_axis,
                     task_generated_at = excluded.task_generated_at")
       ->execute([$course_id, $day_no, $j['task_md'], $target_axis]);

    return [
        'ok'          => true,
        'task_md'     => $j['task_md'],
        'title'       => $j['title'] ?? "Day {$day_no} Practice",
        'target_axis' => $target_axis,
        'from_cache'  => false,
    ];
}


// ─────────────────────────────────────────────────────────────
// Daily recording score — uses eval_clinical's prior computation
// ─────────────────────────────────────────────────────────────
/**
 * Score the child's anchor-sentence recording across 5 axes using ONLY
 * this single recording's data. Saves the snapshot on the day row.
 *
 * @param string $audio_path Relative server path to the recording (optional, for archive)
 * @param string $transcript Web Speech transcript
 * @param array  $acoustic   { transcript_confidence, wpm, silence_ratio, pause_count, time_to_first_speech_sec, duration_sec }
 * @param string $parent_note Optional one-line parent comment
 */
function course_score_daily_recording(int $course_id, int $day_no, ?string $audio_path,
                                       string $transcript, array $acoustic,
                                       string $parent_note = ''): array {
    // Pull course + child
    $st = db()->prepare("SELECT c.*, ch.dob AS child_dob, ch.mother_tongue AS child_mt, ch.name AS child_name
                          FROM eval_courses c JOIN children ch ON ch.id = c.child_id
                          WHERE c.id = ?");
    $st->execute([$course_id]);
    $course = $st->fetch();
    if (!$course) return ['ok' => false, 'error' => 'Course not found'];

    $age_yrs = round((float) calc_age_years($course['child_dob']), 1);
    $is_hindi = $course['anchor_lang'] === 'hi';

    // Build a fake "question" array compatible with _clinical_compute_priors
    // (which expects an array of questions with user_answer + acoustic_json)
    $fake_questions = [[
        'id'             => 0,
        'seq_no'         => 1,
        'level'          => 4,
        'question_type'  => 'describe',
        'prompt'         => $course['anchor_sentence'],
        'user_answer'    => $transcript,
        'is_correct'     => 1,  // always count it
        'time_seconds'   => (int)($acoustic['duration_sec'] ?? 5),
        'acoustic_json'  => json_encode($acoustic, JSON_UNESCAPED_UNICODE),
        'answer_mode'    => 'voice',
    ]];

    // Run the same prior-computation we use in eval_clinical
    $priors = _clinical_compute_priors($fake_questions, $age_yrs, $is_hindi);

    // Build snapshot — score per axis is the prior directly (no Claude call to keep daily flow fast & cheap)
    $snapshot = [];
    foreach (['articulation','fluency','vocabulary','grammar','narrative'] as $k) {
        $snapshot[$k] = (int) ($priors[$k]['score'] ?? 50);
    }
    $snapshot['day_no'] = $day_no;
    $snapshot['recorded_at'] = gmdate('Y-m-d H:i:s');
    $snapshot['transcript_words'] = count(array_filter(preg_split('/[\s,.\?!।]+/u', trim($transcript))));
    $snapshot['wpm'] = (int)($acoustic['wpm'] ?? 0);

    // Persist on the day row
    db()->prepare("INSERT INTO eval_course_days
                   (course_id, day_no, recording_path, transcript, acoustic_json,
                    axis_snapshot_json, parent_note, completed_at, task_md, task_target_axis)
                   VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, '', '')
                   ON CONFLICT(course_id, day_no) DO UPDATE SET
                     recording_path = excluded.recording_path,
                     transcript = excluded.transcript,
                     acoustic_json = excluded.acoustic_json,
                     axis_snapshot_json = excluded.axis_snapshot_json,
                     parent_note = excluded.parent_note,
                     completed_at = CURRENT_TIMESTAMP")
       ->execute([
           $course_id, $day_no, $audio_path, $transcript,
           json_encode($acoustic, JSON_UNESCAPED_UNICODE),
           json_encode($snapshot, JSON_UNESCAPED_UNICODE),
           $parent_note
       ]);

    // Update course last_active_at
    db()->prepare("UPDATE eval_courses SET last_active_at = CURRENT_TIMESTAMP WHERE id = ?")
       ->execute([$course_id]);

    // Auto-complete if day 7
    if ($day_no >= 7) {
        db()->prepare("UPDATE eval_courses SET status = 'completed', completed_at = CURRENT_TIMESTAMP WHERE id = ?")
           ->execute([$course_id]);
    }

    return ['ok' => true, 'snapshot' => $snapshot];
}


// ─────────────────────────────────────────────────────────────
// Progress data for the chart
// ─────────────────────────────────────────────────────────────
/**
 * Returns per-day snapshots ready for charting:
 *
 * [
 *   'days' => [1, 2, 3, ...],            // x-axis labels
 *   'axes' => [
 *     'articulation' => [78, 80, 82, ...],
 *     'fluency'      => [55, 58, 62, ...],
 *     ...
 *   ],
 *   'baseline' => ['articulation' => 70, 'fluency' => 65, ...],  // from original eval
 *   'today_day' => 4,                     // current day in course
 *   'status'    => 'active'|'completed'|'failed',
 *   'anchor_sentence' => '...',
 * ]
 */
function course_progress_data(int $course_id): array {
    $st = db()->prepare("SELECT * FROM eval_courses WHERE id = ?");
    $st->execute([$course_id]);
    $course = $st->fetch();
    if (!$course) return ['error' => 'Course not found'];

    $today = course_today_day($course_id);

    $weak = json_decode($course['weak_axes_json'] ?: '{}', true) ?: [];
    $baseline = $weak['baseline'] ?? [];

    $dst = db()->prepare("SELECT day_no, axis_snapshot_json FROM eval_course_days
                          WHERE course_id = ? AND completed_at IS NOT NULL
                          ORDER BY day_no");
    $dst->execute([$course_id]);
    $rows = $dst->fetchAll();

    $days = [];
    $axes_data = [
        'articulation' => [], 'fluency' => [], 'vocabulary' => [],
        'grammar' => [], 'narrative' => [],
    ];
    foreach ($rows as $r) {
        $days[] = (int)$r['day_no'];
        $snap = json_decode($r['axis_snapshot_json'] ?: '{}', true) ?: [];
        foreach (array_keys($axes_data) as $k) {
            $axes_data[$k][] = isset($snap[$k]) ? (int)$snap[$k] : null;
        }
    }

    return [
        'days'            => $days,
        'axes'            => $axes_data,
        'baseline'        => $baseline,
        'today_day'       => $today['day_no'],
        'status'          => $today['status'],
        'failed_reason'   => $today['failed_reason'],
        'days_since_last' => $today['days_since_last'],
        'anchor_sentence' => $course['anchor_sentence'],
        'anchor_lang'     => $course['anchor_lang'],
        'daily_minutes'   => (int)$course['daily_minutes'],
        'price_paid'      => (int)$course['price_paid'],
        'weak_axes'       => $weak['weak_two'] ?? [],
    ];
}


// ─────────────────────────────────────────────────────────────
// Helper: lookup the parent's active course for a given child
// ─────────────────────────────────────────────────────────────
function course_find_active(int $parent_id, int $child_id): ?array {
    $st = db()->prepare("SELECT * FROM eval_courses
                          WHERE parent_id = ? AND child_id = ? AND status = 'active'
                          ORDER BY id DESC LIMIT 1");
    $st->execute([$parent_id, $child_id]);
    $r = $st->fetch();
    return $r ?: null;
}
